apiVersion: 1

datasources:
  - name: InfluxDB_IoT
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: iot_security_org
      defaultBucket: iot_telemetry
    secureJsonData:
      token: my-super-secret-iot-token-12345
    editable: true
